/**
 * SQL DDL Generator — produces valid SQL for PostgreSQL, MySQL, SQLite, MSSQL
 */

export function generateSQL(schema, dialect) {
  const q = quoteFor(dialect);
  const lines = [];

  lines.push(`-- Generated by ERD Designer`);
  lines.push(`-- Dialect: ${dialect}`);
  lines.push(`-- Generated at: ${new Date().toISOString()}`);
  lines.push('');

  // Disable FK checks
  switch (dialect) {
    case 'postgresql':
      lines.push("SET client_encoding = 'UTF8';");
      break;
    case 'mysql':
      lines.push('SET FOREIGN_KEY_CHECKS = 0;');
      break;
    case 'sqlite':
      lines.push('PRAGMA foreign_keys = OFF;');
      break;
    case 'mssql':
      // MSSQL uses GO separators
      break;
  }
  lines.push('');

  const entities = Object.values(schema.entities);
  const relations = Object.values(schema.relations);

  // CREATE TABLE statements
  for (const entity of entities) {
    const tableDef = generateTable(entity, schema, dialect, q, relations);
    lines.push(tableDef);
    lines.push('');
  }

  // Foreign key constraints (ALTER TABLE) for non-SQLite
  if (dialect !== 'sqlite') {
    for (const relation of relations) {
      const sourceEntity = schema.entities[relation.sourceEntityId];
      const targetEntity = schema.entities[relation.targetEntityId];
      if (!sourceEntity || !targetEntity) continue;
      const sourceAttr = sourceEntity.attributes.find((a) => a.id === relation.sourceAttributeId);
      const targetAttr = targetEntity.attributes.find((a) => a.id === relation.targetAttributeId);
      if (!sourceAttr || !targetAttr) continue;

      const fkLine = `ALTER TABLE ${q(sourceEntity.name)}`;
      const constraintLine = `  ADD CONSTRAINT ${q(relation.name)}`;
      const fkRefLine = `  FOREIGN KEY (${q(sourceAttr.name)})`;
      const refLine = `  REFERENCES ${q(targetEntity.name)}(${q(targetAttr.name)})`;
      const actions = [];
      if (relation.onDelete && relation.onDelete !== 'NO ACTION') {
        actions.push(`  ON DELETE ${relation.onDelete}`);
      }
      if (relation.onUpdate && relation.onUpdate !== 'NO ACTION') {
        actions.push(`  ON UPDATE ${relation.onUpdate}`);
      }

      lines.push(fkLine);
      lines.push(constraintLine);
      lines.push(fkRefLine);
      lines.push(refLine + (actions.length ? '' : ';'));
      for (let i = 0; i < actions.length; i++) {
        lines.push(actions[i] + (i === actions.length - 1 ? ';' : ''));
      }
      lines.push('');
      if (dialect === 'mssql') lines.push('GO');
    }
  }

  // Re-enable FK checks
  lines.push('');
  switch (dialect) {
    case 'mysql':
      lines.push('SET FOREIGN_KEY_CHECKS = 1;');
      break;
    case 'sqlite':
      lines.push('PRAGMA foreign_keys = ON;');
      break;
  }

  return lines.join('\n');
}

function generateTable(entity, schema, dialect, q, relations) {
  const lines = [];
  const isMySQL = dialect === 'mysql';
  const isSQLite = dialect === 'sqlite';
  const isMSSQL = dialect === 'mssql';
  const isPG = dialect === 'postgresql';

  lines.push(`CREATE TABLE IF NOT EXISTS ${q(entity.name)} (`);

  const colDefs = [];
  const pkCols = [];

  for (const attr of entity.attributes) {
    let def = `  ${q(attr.name)} ${mapType(attr, dialect)}`;

    if (attr.isPrimaryKey && !isMySQL) {
      // For PG/SQLite/MSSQL, inline PRIMARY KEY for single-col PK
      const pkCount = entity.attributes.filter((a) => a.isPrimaryKey).length;
      if (pkCount === 1 && !isMSSQL) {
        def += ' PRIMARY KEY';
        if (attr.isAutoIncrement && isSQLite) {
          def += ' AUTOINCREMENT';
        }
      }
    }

    if (attr.isPrimaryKey) pkCols.push(attr.name);

    if (attr.isNotNull && !attr.isPrimaryKey) {
      def += ' NOT NULL';
    }

    if (attr.isUnique && !attr.isPrimaryKey) {
      def += ' UNIQUE';
    }

    if (attr.defaultValue !== null && attr.defaultValue !== undefined && attr.defaultValue !== '') {
      def += ` DEFAULT ${attr.defaultValue}`;
    }

    // Inline FK for SQLite
    if (isSQLite) {
      const rel = relations.find(
        (r) => r.sourceEntityId === entity.id && r.sourceAttributeId === attr.id
      );
      if (rel) {
        const targetEntity = schema.entities[rel.targetEntityId];
        const targetAttr = targetEntity?.attributes.find((a) => a.id === rel.targetAttributeId);
        if (targetEntity && targetAttr) {
          def += ` REFERENCES ${q(targetEntity.name)}(${q(targetAttr.name)})`;
          if (rel.onDelete && rel.onDelete !== 'NO ACTION') def += ` ON DELETE ${rel.onDelete}`;
          if (rel.onUpdate && rel.onUpdate !== 'NO ACTION') def += ` ON UPDATE ${rel.onUpdate}`;
        }
      }
    }

    colDefs.push(def);
  }

  // Table-level PK for MySQL and MSSQL
  if ((isMySQL || isMSSQL) && pkCols.length > 0) {
    colDefs.push(`  PRIMARY KEY (${pkCols.map(q).join(', ')})`);
  }

  lines.push(colDefs.join(',\n'));
  lines.push(')' + (isMySQL ? ' ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;' : ';'));

  if (isMSSQL) lines.push('GO');

  return lines.join('\n');
}

function mapType(attr, dialect) {
  const type = attr.type.toUpperCase();

  // Handle auto-increment types
  if (attr.isAutoIncrement && attr.isPrimaryKey) {
    switch (dialect) {
      case 'postgresql':
        if (type.includes('BIGINT')) return 'BIGSERIAL';
        return 'SERIAL';
      case 'mysql':
        return (type.includes('BIGINT') ? 'BIGINT' : 'INT') + ' NOT NULL AUTO_INCREMENT';
      case 'sqlite':
        return 'INTEGER'; // AUTOINCREMENT added separately
      case 'mssql':
        return (type.includes('BIGINT') ? 'BIGINT' : 'INT') + ' IDENTITY(1,1) NOT NULL';
    }
  }

  // Dialect-specific mappings
  switch (dialect) {
    case 'postgresql':
      if (type === 'DATETIME') return 'TIMESTAMP';
      if (type === 'DOUBLE') return 'DOUBLE PRECISION';
      if (type === 'BLOB') return 'BYTEA';
      if (type === 'TINYINT' || type === 'TINYINT(1)') return 'BOOLEAN';
      break;
    case 'mysql':
      if (type === 'BOOLEAN') return 'TINYINT(1)';
      if (type === 'BYTEA') return 'BLOB';
      if (type === 'SERIAL') return 'INT AUTO_INCREMENT';
      if (type === 'TIMESTAMP') return 'TIMESTAMP';
      break;
    case 'sqlite':
      if (type.startsWith('VARCHAR')) return 'TEXT';
      if (type.startsWith('CHAR')) return 'TEXT';
      if (type === 'BOOLEAN') return 'INTEGER';
      if (type.startsWith('DECIMAL') || type.startsWith('NUMERIC')) return 'REAL';
      if (type === 'TIMESTAMP' || type === 'DATETIME') return 'TEXT';
      if (type === 'BYTEA') return 'BLOB';
      break;
    case 'mssql':
      if (type === 'BOOLEAN') return 'BIT';
      if (type === 'TEXT') return 'NVARCHAR(MAX)';
      if (type === 'TIMESTAMP') return 'DATETIME2';
      if (type === 'DOUBLE') return 'FLOAT';
      if (type === 'BYTEA' || type === 'BLOB') return 'VARBINARY(MAX)';
      if (type === 'SERIAL') return 'INT IDENTITY(1,1)';
      break;
  }

  return attr.type;
}

function quoteFor(dialect) {
  switch (dialect) {
    case 'mysql':
      return (name) => '`' + name + '`';
    case 'mssql':
      return (name) => '[' + name + ']';
    default:
      return (name) => '"' + name + '"';
  }
}
